#!/usr/bin/env bash

#
# Update script using terminus + drush to apply
# Arizona Quickstart 3 upstream & Config Distro updates
# LIVE instances
#

if [[ -z ${SITE_NAME} ]]; then
    echo -e "\e[31mError: SITE_NAME must be set\e[0m"
    exit 1
fi

echo ""
echo -e "\e[33;44m---Updating ${SITE_NAME}.live---\e[0m"
echo ""

# Wake dev site
terminus env:wake -- ${SITE_NAME}.live

# Create a backup of the dev instance
terminus backup:create ${SITE_NAME}.live

# Deploy upstream updates
terminus env:deploy ${SITE_NAME}.live --updatedb --note="Deploy core and contrib updates"

AZQS3="8d8f8753-0cbc-46e1-aee6-e628f720a798"
CURRENT_UPSTREAM=$(terminus site:info ${SITE_NAME} --field upstream | sed 's/:.*$//g')
if [[ "${CURRENT_UPSTREAM}" == "${AZQS3}" ]]; then
  terminus drush ${SITE_NAME}.live -- -n -y updatedb
  terminus drush ${SITE_NAME}.live -- -n -y state:set config_sync.update_mode 1 --input-format=integer
  terminus drush ${SITE_NAME}.live -- -n -y config-distro-update
  terminus drush ${SITE_NAME}.live -- -n -y az-core-config-add-permissions
fi

# clear & rebuild caches
terminus env:clear-cache ${SITE_NAME}.live
terminus drush ${SITE_NAME}.live -- -n -y cache:rebuild

