#!/usr/bin/env bash

#
# Update script using terminus + drush to apply
# Arizona Quickstart 2 upstream & Config Distro updates:
# DEV instances
#

if [[ -z ${SITE_NAME} ]]; then
    echo -e "\e[31mError: SITE_NAME must be set\e[0m"
    exit 1
fi

echo ""
echo -e "\e[33;44m---Updating ${SITE_NAME}.dev---\e[0m"
echo ""

# Wake dev site
terminus env:wake -- ${SITE_NAME}.dev

# Create a backup of the dev instance
terminus backup:create ${SITE_NAME}.dev

# Clear upstream cache and apply updates
terminus site:upstream:clear-cache ${SITE_NAME}
terminus upstream:updates:status ${SITE_NAME}.dev
terminus upstream:updates:apply --accept-upstream -- ${SITE_NAME}.dev

# If AZQS, run extra drush steps
AZQS2="3162cc4c-2f75-40cb-8487-0c69bda99f39"
AZQS3="8d8f8753-0cbc-46e1-aee6-e628f720a798"
CURRENT_UPSTREAM=$(terminus site:info ${SITE_NAME} --field upstream | sed 's/:.*$//g')
if [[ "${CURRENT_UPSTREAM}" == "${AZQS3}" ]]; then
  terminus drush ${SITE_NAME}.dev -- -n -y updatedb
  terminus drush ${SITE_NAME}.dev -- -n -y state:set config_sync.update_mode 1 --input-format=integer
  terminus drush ${SITE_NAME}.dev -- -n -y config-distro-update --update-mode=1
  terminus drush ${SITE_NAME}.dev -- -n -y az-core-config-add-permissions
fi

terminus env:clear-cache ${SITE_NAME}.dev
terminus drush ${SITE_NAME}.dev -- -n -y cache:rebuild

